services:
  - type: web
    name: aadamautotrades
    env: python
    pythonVersion: "3.12.7"  # FIXED VERSION
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
